### ISSUE TITLE
const files = [...extracted.files] Hangs Entire Application

### ISSUE THREAD

**Issue by c9win** [YuJianrong/node-unrar.js#11]
Hello, for some reason, when I run the command `const files = [...extracted.files]` it hangs my entire application. I have an app that downloads files, then is trying to unrar it. The files are only ~400mb, but, the whole app hangs on this line for ~5 seconds. Shows Not Responding on windows and the beachball on mac. 

It is highly possible I am doing something wrong either in my node app or with this package. Any ideas on how to do this without hanging the rest of the application?

Thank you for your time.

**Comment by YuJianrong** [comment]
It's normal for nodejs to take 5 seconds to extract 400mb rar file. Sorry but it's almost impossible to make this library asynchronized since async call to wasm library is super complicated in this case.

Please try to use [worker thread](https://nodejs.org/api/worker_threads.html) in nodejs to put the extraction in another thread so the main thread will not be blocked. I didn't tried it but it should works.

**Comment by c9win** [comment]
Thank you!! It did work, but I ended up using a webworker instead of the worker thread (electron app). Appreciate it and thank you for making this!!
