### ISSUE TITLE
How unrar parts 

### ISSUE THREAD

**Issue by EdwinAlmendras** [YuJianrong/node-unrar.js#6]
Its posibble to unrar files rar like this:

archive.001.rar
archive.002.rar
archive.003.rar

How can extract this ?

**Comment by YuJianrong** [comment]
> Its posibble to unrar files rar like this:
> 
> archive.001.rar
> archive.002.rar
> archive.003.rar
> 
> How can extract this ?

It's not supported. Sorry I have no time to fix it now, PR is welcome :)

**Comment by EdwinAlmendras** [comment]
Ok no problem. One question more ..
On createExtractorFromData get buffer

And How can receive stream? 
Because when im trying to extract large files my computer collapse
Thanks!!!

**Comment by YuJianrong** [comment]
The best solution to extract big file is extracting from file system instead of memory.
One possible solution to make `createExtractorFromData` output stream is change the `write` method in `src/js/ExtractorData.helper.ts`, it's the only place to get the data for memory extraction. Note the in-memory file is created in method `create` in `src/js/ExtractorData.ts`. You can try to modify these two functions to get the output in streaming.
